baseURL = "https://lokal.ninja/mecklenburg-vorpommern"
languageCode = "de-DE"
title = "Lokal Ninja - Mecklenburg-Vorpommern"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Mecklenburg-Vorpommern"
  repo = "mecklenburg-vorpommern"
